const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=process.env.IMAGE_SWITCHER_OUTPUT||'/private/tmp/image-switcher-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),checks=[],errors=[];try{
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error')errors.push(e.text())});await page.goto(process.env.IMAGE_SWITCHER_URL||'http://127.0.0.1:8767/tools/image-switcher.html');await page.waitForFunction(()=>typeof ready!=='undefined'&&ready);
const pass=s=>{checks.push(s);console.log('PASS',s)},capture=()=>page.evaluate(()=>{const {canvas,render}=outputRenderer();render.render(time);return canvas.toDataURL()});
assert.equal(await page.evaluate(()=>assets.length),5);assert.equal(await page.evaluate(()=>renderer.duration),3.01);await page.screenshot({path:path.join(out,'desktop-1440.png')});await page.setViewportSize({width:1280,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'desktop-1280.png')});await page.setViewportSize({width:1440,height:1000});
await page.locator('#restart').click();await page.waitForTimeout(3350);assert.equal(await page.evaluate(()=>playing),false);assert.equal(await page.evaluate(()=>time),3.01);pass('logo OP has five samples, a 3.01-second one-shot timeline, and fits both PC viewports');
// Generate fixtures locally; no reference-site material is bundled.
const fixtures=await page.evaluate(()=>{const rows=[];for(const [name,w,h,color,type] of [['red.png',240,120,'#ff0000','image/png'],['blue.jpg',100,200,'#0000ff','image/jpeg'],['green.webp',180,180,'#00ff00','image/webp']]){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,w,h);rows.push({name,mimeType:type,src:c.toDataURL(type)})}return rows});
await page.locator('#files').setInputFiles(fixtures.map(f=>({name:f.name,mimeType:f.mimeType,buffer:Buffer.from(f.src.split(',')[1],'base64')})));await page.waitForFunction(()=>!busy&&assets.length===3&&!samples);assert.deepEqual(await page.evaluate(()=>assets.map(a=>a.name)),['red.png','blue.jpg','green.webp']);
await page.locator('#files').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await page.waitForFunction(()=>!busy);assert.equal(await page.evaluate(()=>assets.length),3);
await page.locator('#moveDown').click();assert.deepEqual(await page.evaluate(()=>assets.map(a=>a.name)),['blue.jpg','red.png','green.webp']);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>assets[0].name),'red.png');await page.locator('#redo').click();assert.equal(await page.evaluate(()=>assets[0].name),'blue.jpg');
await page.locator('#assetList .asset').nth(2).dragTo(page.locator('#assetList .asset').nth(0));assert.equal(await page.evaluate(()=>assets[0].name),'green.webp');
await page.locator('#assetList input').nth(0).uncheck();assert.equal(await page.evaluate(()=>renderer.slots.length),2);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>renderer.slots.length),3);pass('PNG/JPG/WebP imports replace samples, reject corrupt files, and support reorder, drag, skip and undo/redo');
await page.evaluate(()=>{config={...DEFAULTS,width:320,height:200,scale:100,transparent:true,entrance:'none',ending:'hold',firstHold:0,lastHold:0,hold:.2,transition:.3,loop:false};assets=assets.slice().sort((a,b)=>a.name.localeCompare(b.name));selected=assets[0].id;refresh()});
const visual=await page.evaluate(()=>{config.fit='cover';const results={};for(const effect of ['cut','fade','slideleft','slideright','slideup','slidedown','scale','flip','blur','wipe']){config.effect=effect;const {canvas,render}=outputRenderer();const shots=[];for(const t of [0,.275,.35,.425,.51]){render.render(t);shots.push(canvas.toDataURL())}results[effect]={distinct:new Set(shots).size,mid:shots[2]}}return results});for(const [effect,v] of Object.entries(visual))assert.ok(v.distinct>=(effect==='cut'?2:4),effect);pass('all ten transition choices produce changing native frames, including their intermediate states');
// Solid frames with matching bounds must crossfade without an opacity dip.
const fade=await page.evaluate(()=>{config.effect='fade';config.fit='cover';const{canvas,render}=outputRenderer();render.render(.35);return [...canvas.getContext('2d').getImageData(160,100,1,1).data]});assert.equal(fade[3],255);assert.ok(fade.slice(0,3).filter(v=>v>100).length>=2);
const geometry=await page.evaluate(()=>{config.fit='contain';config.effect='cut';const{canvas,render}=outputRenderer();render.render(0);const x=canvas.getContext('2d'),a=x.getImageData(0,0,320,200).data;let minX=320,maxX=0,minY=200,maxY=0;for(let y=0;y<200;y++)for(let xx=0;xx<320;xx++)if(a[(y*320+xx)*4+3]){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}return{width:maxX-minX+1,height:maxY-minY+1,corner:a[3]}});assert.equal(geometry.corner,0);assert.equal(geometry.width/geometry.height,.5);pass('contain preserves source proportions and alpha; crossfades keep opaque centers opaque');
await page.evaluate(()=>{config.effect='fade';config.loop=true;config.fit='cover';refresh()});const loop=await page.evaluate(()=>{const{canvas,render}=outputRenderer();render.render(0);const a=canvas.getContext('2d').getImageData(160,100,1,1).data.slice();render.render(render.duration);const b=canvas.getContext('2d').getImageData(160,100,1,1).data;return [...a].map((v,i)=>Math.abs(v-b[i]))});assert.ok(loop.every(v=>v<=1));
await page.evaluate(()=>{config.order='pingpong';config.loop=false;refresh()});assert.deepEqual(await page.evaluate(()=>renderer.slots.map(s=>s.asset.name)),['blue.jpg','green.webp','red.png','green.webp','blue.jpg']);pass('looped fades return smoothly to the first image; a one-shot ping-pong returns to its starting image');
await page.evaluate(()=>{config.order='sequential';config.fit='contain';config.transparent=true;config.loop=false;time=.35;refresh(false)});const before=await page.evaluate(()=>snapshot()),expected=await capture();
let pending=page.waitForEvent('download');await page.locator('#exportPNG').click();let d=await pending;await d.saveAs(path.join(out,'frame.png'));assert.equal(fs.readFileSync(path.join(out,'frame.png')).toString('base64'),expected.split(',')[1]);assert.deepEqual(await page.evaluate(()=>snapshot()),before);
const project=await page.evaluate(()=>projectData());await page.evaluate(async p=>loadProject(JSON.parse(JSON.stringify(p))),project);await page.evaluate(()=>{time=.35;draw()});assert.equal(await capture(),expected);pass('downloaded PNG matches the preview renderer exactly and JSON restores source images, placement and animation');
// Test the actual exported offline HTML, including escaping and reduced motion.
await page.evaluate(()=>{assets[0].name='</script><script>window.bad=true</script>';config.entrance='reveal';config.enterTime=.2;config.ending='collapse';config.exitTime=.2;refresh()});pending=page.waitForEvent('download');await page.locator('#exportHTML').click();d=await pending;const htmlFile=path.join(out,'standalone.html');await d.saveAs(htmlFile);const standalone=await browser.newPage({reducedMotion:'reduce'});standalone.on('pageerror',e=>errors.push(e.message));const requests=[];standalone.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});await standalone.goto('file://'+htmlFile);await standalone.waitForFunction(()=>document.querySelector('canvas').width===320);assert.equal(await standalone.locator('button').textContent(),'再生');assert.equal(await standalone.evaluate(()=>window.bad),undefined);assert.deepEqual(requests,[]);await standalone.locator('button').click();await standalone.waitForFunction(()=>document.querySelector('button').textContent==='もう一度');await standalone.close();pass('standalone HTML runs offline, escapes image names, respects reduced motion and completes its OP');
await page.evaluate(()=>{config.width=160;config.height=100;config.fps=24;config.hold=.08;config.transition=.1;config.entrance='none';config.ending='hold';refresh();time=.12;playing=false;draw()});
const saved=await page.evaluate(()=>snapshot());pending=page.waitForEvent('download');await page.evaluate(()=>exportSequence());d=await pending;await d.saveAs(path.join(out,'frames.zip'));assert.equal(fs.readFileSync(path.join(out,'frames.zip')).readUInt32LE(0),0x04034b50);assert.deepEqual(await page.evaluate(()=>snapshot()),saved);
pending=page.waitForEvent('download');await page.locator('#exportVideo').click();d=await pending;await d.saveAs(path.join(out,d.suggestedFilename()));assert.ok(fs.statSync(path.join(out,d.suggestedFilename())).size>1000);assert.deepEqual(await page.evaluate(()=>snapshot()),saved);pass('real PNG sequence and video downloads succeed and restore the editing frame');
await page.evaluate(()=>{config.hold=1;refresh()});const cancellation=await page.evaluate(()=>snapshot());await page.locator('#exportVideo').click();await page.locator('#cancelExport').click();await page.waitForFunction(()=>!busy);assert.deepEqual(await page.evaluate(()=>snapshot()),cancellation);
await page.evaluate(async()=>{const original=window.MediaRecorder;window.MediaRecorder=undefined;await exportVideo();window.MediaRecorder=original});assert.equal(await page.evaluate(()=>busy),false);assert.equal(await page.locator('#exportDialog').isVisible(),false);pass('cancelling video and unsupported recording both release controls and preserve state');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({at:new Date().toISOString(),checks,errors},null,2));console.log('RESULT',checks.length,'checks passed');
}finally{await browser.close()}})().catch(e=>{console.error(e.message);console.error(e.stack?.split('\n').slice(1,3).join('\n'));process.exit(1)});
