// Saved PNGs must stay smooth across resolutions, including steep color ramps.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.THERMAL_PLAYWRIGHT_MODULE||'playwright');
const baseline=process.env.THERMAL_QUALITY_BASELINE_FILE;
const out=process.env.THERMAL_QUALITY_OUTPUT||'/private/tmp/thermal-quality-qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true});const checks=[],errors=[],metrics={};
try{
const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.message));
const note=s=>{checks.push(s);console.log('PASS',s)};
const open=async useBaseline=>{if(useBaseline)await page.route('**/tools/thermal-flow.html',r=>r.fulfill({contentType:'text/html',body:fs.readFileSync(baseline,'utf8')}));else await page.unroute('**/tools/thermal-flow.html');await page.goto(process.env.THERMAL_URL||'http://127.0.0.1:8766/tools/thermal-flow.html');await page.waitForFunction(()=>document.querySelectorAll('[data-ready=true]').length===PRESETS.length,{},{timeout:90000})};
const configure=async()=>page.evaluate(()=>{applyPreset(PRESETS.find(p=>p.name==='グラデ'));Object.assign(state.field,{mode:'linear',linShape:'line',linAng:0,linWidth:400,warp1:0,warp2:0,curl:0,rise:0,gamma:50,contrast:50,offset:0,norm:false,linPosition:0});state.grain.amount=0;state.motion.on=false;state.mask.on=false;state.pins=[];state.studio=clone(DEFAULT_STUDIO);state.studio.gradient.interp='linear';state.finish.bg=0;state.canvas={mode:'custom',w:1200,h:300};state.lut={stops:[{p:0,c:'#080808',h:0},{p:.45,c:'#080808',h:0},{p:.55,c:'#f8f8f8',h:0},{p:1,c:'#f8f8f8',h:0}],bands:0,invert:false,shift:0};buildLut();refreshAll();redraw()});
const save=async(name,mult=1,format='png')=>{const pending=page.waitForEvent('download');await page.evaluate(async({mult,format})=>exportStill(format,mult),{mult,format});const d=await pending,file=path.join(out,name);await d.saveAs(file);return fs.readFileSync(file).toString('base64')};
const measure=async(data,format='png')=>page.evaluate(async({data,format})=>{const img=new Image();img.src='data:image/'+format+';base64,'+data;await img.decode();const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const ctx=c.getContext('2d');ctx.drawImage(img,0,0);const a=ctx.getImageData(0,0,c.width,c.height).data;let maxSpread=0,sumSpread=0,n=0;for(let x=Math.floor(c.width*.46);x<Math.floor(c.width*.54);x++){let lo=255,hi=0;for(let y=0;y<c.height;y+=3){const value=a[(y*c.width+x)*4];lo=Math.min(lo,value);hi=Math.max(hi,value)}maxSpread=Math.max(maxSpread,hi-lo);sumSpread+=hi-lo;n++}return{width:c.width,height:c.height,maxSpread,meanSpread:sumSpread/n}},{data,format});
if(baseline){await open(true);await configure();metrics.before=await measure(await save('before.png'));assert.ok(metrics.before.maxSpread>8,JSON.stringify(metrics.before));note('reproduced visible export speckles with grain set to zero');}
await open(false);
assert.equal(await page.evaluate(()=>state.grain.amount),0);assert.ok(await page.evaluate(()=>PRESETS.every(p=>p.grain.amount===0)&&DEFAULT_STUDIO.noise.amount===0));note('fresh document and all looks start with zero grain');
await configure();const before=await page.evaluate(()=>stateRecord());
for(const mult of [1,2,4]){metrics['after'+mult]=await measure(await save('after-'+mult+'x.png',mult));assert.equal(metrics['after'+mult].width,1200*mult);assert.equal(metrics['after'+mult].height,300*mult);assert.ok(metrics['after'+mult].maxSpread<=2,JSON.stringify(metrics['after'+mult]));assert.deepEqual(await page.evaluate(()=>stateRecord()),before)}note('actual 1×, 2× and 4× PNGs retain smooth boundaries and do not alter the document');
await page.evaluate(()=>{state.studio.gradient.interp='linear';state.lut.stops=[{p:0,c:'#000000',h:0},{p:1,c:'#ffffff',h:0}];buildLut()});
const ramp=await save('linear-ramp.png');
metrics.ramp=await page.evaluate(async data=>{const im=new Image();im.src='data:image/png;base64,'+data;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const a=ctx.getImageData(0,0,c.width,c.height).data;let maxError=0;for(let x=0;x<c.width;x++){let sum=0;for(let y=0;y<c.height;y++)sum+=a[(y*c.width+x)*4];maxError=Math.max(maxError,Math.abs(sum/c.height-(x+.5)/c.width*255))}return{maxError}},ramp);assert.ok(metrics.ramp.maxError<.25,JSON.stringify(metrics.ramp));note('grayscale ramp follows the unquantized reference without baked-in 8-bit plateaus');
await configure();await page.evaluate(()=>{state.grain.amount=60;buildLut()});metrics.grain=await measure(await save('grain-60.png'));assert.ok(metrics.grain.maxSpread>30);const saved=await page.evaluate(()=>projectSnapshot());await page.evaluate(p=>loadProject(p),saved);assert.equal(await page.evaluate(()=>state.grain.amount),60);note('intentional grain still works and saved projects retain their amount');
await configure();await page.evaluate(()=>{state.lut.bands=4;buildLut()});metrics.bands=await measure(await save('bands.png'));assert.ok(metrics.bands.maxSpread<=2);note('intentional posterized bands retain clean boundaries');
await page.evaluate(()=>{applyPreset(PRESETS.find(p=>p.name==='溶融プール'));state.canvas={mode:'custom',w:1200,h:800};refreshAll();redraw()});await save('molten-pool.png');
await page.evaluate(()=>{state.mask.on=true;state.mask.transparent=true;state.mask.text='Flow';state.mask.text2='';refreshAll();redraw()});const mask=await measure(await save('masked.png'));assert.ok(mask.width<1200&&mask.height<800);note('molten colors render correctly and masked exports still trim');
for(const format of ['jpeg','webp']){const m=await measure(await save('masked.'+(format==='jpeg'?'jpg':format),1,format),format);assert.equal(m.width,mask.width);assert.equal(m.height,mask.height)}note('JPG and WebP exports retain the same cropped geometry');
assert.deepEqual(errors,[]);console.log(JSON.stringify(metrics));fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({at:new Date().toISOString(),checks,metrics,errors},null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
