// Circle transparency must exist in the artwork itself, independent of CSS or export format.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.THERMAL_PLAYWRIGHT_MODULE||'playwright');
const out=process.env.THERMAL_ALPHA_OUTPUT||'/private/tmp/thermal-circle-alpha';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),errors=[],checks=[],measurements=[];try{
 const base=process.env.THERMAL_URL||'http://127.0.0.1:8766/tools/thermal-flow.html';
 const skip=s=>s.replace(/requestAnimationFrame\(loop\);\s*renderLookThumbnails\(\);/,'requestAnimationFrame(loop);');
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route('**/tools/thermal-flow.html*',async route=>{const response=await route.fetch();await route.fulfill({response,body:skip(await response.text())});});
 await page.goto(base+'?p='+encodeURIComponent('サーモフレーム'));await page.waitForFunction(()=>typeof quick!=='undefined'&&quick);
 const note=t=>{checks.push(t);console.log('PASS',t)};
 const reset=()=>page.evaluate(()=>{applyPreset(PRESETS.find(p=>p.name==='サーモフレーム'));setPalette(LUT_PRESETS.find(p=>p.name==='基準サーモ'));Object.assign(state.field,{frameShape:'circle',frameSize:90});Object.assign(state.canvas,{mode:'custom',w:360,h:360});Object.assign(state.mask,{on:false,transparent:true});Object.assign(state.studio.image,{on:false,data:''});overlayImage=null;overlayImageKey='';state.studio.stretch.on=false;refreshAll();redraw();});
 const capture=({w=360,h=360,crop=false}={})=>page.evaluate(({w,h,crop})=>{renderGL(w,h,1);const source=crop?prepareExportArtwork(w,h):composeArtwork(w,h);const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const x=c.getContext('2d');x.drawImage(source,0,0);const pixels=x.getImageData(0,0,c.width,c.height).data;let clear=0,solid=0,partial=0;const edges=[false,false,false,false];for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++){const a=pixels[(y*c.width+xx)*4+3];if(!a)clear++;else{if(a===255)solid++;else partial++;if(!xx)edges[0]=true;if(!y)edges[1]=true;if(xx===c.width-1)edges[2]=true;if(y===c.height-1)edges[3]=true}}const center=(Math.floor(c.height/2)*c.width+Math.floor(c.width/2))*4;return{png:c.toDataURL(),width:c.width,height:c.height,clear,solid,partial,edges,corner:[...pixels.slice(0,4)],center:[...pixels.slice(center,center+4)],bounds:alphaBounds(source),glError:gl.getError(),checker:view.classList.contains('transparent-artwork')};},{w,h,crop});
 const save=(name,png)=>fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(png.split(',')[1],'base64'));
 const record=()=>page.evaluate(()=>stateRecord());
 await reset();
 for(const [w,h] of [[360,540],[540,360],[360,360]]){const img=await capture({w,h});assert.equal(img.glError,0);assert.equal(img.corner[3],0);assert.equal(img.center[3],255);assert.ok(img.center.slice(0,3).every((v,i)=>Math.abs(v-[242,229,216][i])<=1));assert.ok(img.clear>w*h*.2&&img.partial>100);assert.equal(img.checker,true);assert.ok(Math.abs(img.bounds.width-img.bounds.height)<=1);save('circle-'+w+'-'+h,img.png);const{png,...stats}=img;measurements.push(stats);}
 note('circle exterior has zero alpha; center stays opaque with the approved skin color in three aspect ratios');
 const original=await record(),raw=await capture(),cropped=await capture({crop:true});assert.ok(cropped.width<raw.width&&cropped.height<raw.height);assert.equal(cropped.width,cropped.height);assert.ok(cropped.edges.every(Boolean));assert.equal(cropped.corner[3],0);assert.ok(cropped.partial>100);assert.deepEqual(await record(),original);
 await page.evaluate(()=>{state.field.frameSize=40;refreshAll()});const smaller=await capture();assert.ok(smaller.bounds.width<raw.bounds.width*.5);await reset();
 note('still exports trim to nonzero alpha, retain antialiased pixels, and leave the editing canvas unchanged');
 // Real downloads and clipboard use exactly the same RGBA artwork.
 const expected=await capture({w:1080,h:1080,crop:true});await page.evaluate(()=>{state.canvas.mode='11';refreshAll()});const before=await record();const pending=page.waitForEvent('download');await page.locator('#btnPng1').click();const download=await pending;await download.saveAs(path.join(out,'circle-transparent.png'));const file=fs.readFileSync(path.join(out,'circle-transparent.png'));assert.equal(file.toString('base64'),expected.png.split(',')[1]);assert.equal(file.readUInt32BE(16),expected.width);assert.ok(download.suggestedFilename().includes(expected.width+'x'+expected.height));assert.deepEqual(await record(),before);
 await page.evaluate(()=>{window.copied=null;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{write:async items=>{const blob=await items[0].getType('image/png');const reader=new FileReader();window.copied=await new Promise(resolve=>{reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob)})}}});document.querySelector('#exportMore').open=true;});await page.locator('#btnCopy').click();await page.waitForFunction(()=>window.copied);assert.equal(await page.evaluate(()=>window.copied),expected.png);
 note('downloaded 1080px PNG and copied image preserve identical cropped RGBA pixels');
 // An opaque mask background or an image layer must not refill the exterior.
 await reset();await page.evaluate(()=>{Object.assign(state.mask,{on:true,transparent:false,text:'FLOW',text2:'',size:35});refreshAll()});const masked=await capture();assert.equal(masked.corner[3],0);assert.ok(masked.clear>1000&&masked.solid>1000);assert.ok((await capture({crop:true})).width>0);
 await reset();await page.evaluate(async()=>{const cv=document.createElement('canvas');cv.width=4;cv.height=4;const c=cv.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,4,4);overlayImage=new Image();overlayImage.src=cv.toDataURL();await overlayImage.decode();overlayImageKey=overlayImage.src;Object.assign(state.studio.image,{on:true,data:overlayImage.src,mode:'overlay',size:200,opacity:1});});const overlay=await capture();assert.equal(overlay.corner[3],0);assert.deepEqual(overlay.center,[255,255,255,255]);
 await reset();await page.evaluate(()=>Object.assign(state.studio.stretch,{on:true,glow:true,glowThreshold:0,glowRadius:40,amount:0,bandHeight:0}));const glow=await capture();assert.equal(glow.corner[3],0);assert.equal(glow.bounds.width,raw.bounds.width);
 note('opaque mask backgrounds, image overlays and glow remain clipped to the circular artwork');
 await reset();const current=await record(),png=(await capture()).png,hash=await page.evaluate(()=>encodeState());await page.evaluate(()=>{state.field.frameShape='rect';refreshAll()});const rect=await capture();assert.equal(rect.clear,0);assert.equal(rect.checker,false);await page.evaluate(h=>{decodeState(h);restoreFramePlayback();buildLut();refreshAll()},hash);assert.equal((await capture()).png,png);assert.deepEqual((await record()).field,current.field);
 const frames=await page.evaluate(()=>{_recording=true;state.motion.on=true;const result=[];for(const t of [0,2,8]){setAnimPhase(t);renderGL(180,180,1);const p=new Uint8Array(4);gl.readPixels(0,0,1,1,gl.RGBA,gl.UNSIGNED_BYTE,p);result.push({png:view.toDataURL(),alpha:p[3]})}_recording=false;state.motion.on=false;restoreFramePlayback();return result});assert.ok(frames.every(f=>f.alpha===0));assert.notEqual(frames[0].png,frames[1].png);assert.equal(frames[0].png,frames[2].png);
 note('transparency survives URL restore and every loop frame; switching to a rectangle restores opaque output');
 // Check unchanged pixels with the previous renderer, not just a similar appearance.
 const baseline=process.env.THERMAL_ALPHA_BASELINE_FILE;
 if(baseline){const old=await browser.newPage();await old.route('**/tools/thermal-flow.html*',r=>r.fulfill({contentType:'text/html',body:skip(fs.readFileSync(baseline,'utf8'))}));await old.goto(base);await old.waitForFunction(()=>typeof quick!=='undefined'&&quick);
 for(const name of ['サーモフレーム','四隅フレア','溶融リボン','KVスワール','グラデ','ラジアル']){const snap=name=>{applyPreset(PRESETS.find(p=>p.name===name));renderGL(180,240,1);return view.toDataURL()};assert.equal(await page.evaluate(snap,name),await old.evaluate(snap,name),name)}
 const sample=()=>{applyPreset(PRESETS.find(p=>p.name==='サーモフレーム'));setPalette(LUT_PRESETS.find(p=>p.name==='基準サーモ'));state.field.frameShape='circle';renderGL(240,240,1);const px=new Uint8Array(240*240*4);gl.readPixels(0,0,240,240,gl.RGBA,gl.UNSIGNED_BYTE,px);const inner=[];for(let y=0;y<240;y++)for(let x=0;x<240;x++)if(Math.hypot(x+.5-120,y+.5-120)<106)inner.push(...px.slice((y*240+x)*4,(y*240+x)*4+4));return inner};assert.deepEqual(await page.evaluate(sample),await old.evaluate(sample));await old.close();note('circle interior and all six existing looks remain pixel-identical to the previous renderer');}
 await reset();await page.evaluate(()=>{state.canvas.mode='11';Object.assign(state.field,{frameTopReach:135,frameRightReach:65,frameBottomReach:100,frameLeftReach:85,frameTopLean:35,frameRightStrength:65});refreshAll();document.querySelector('#exportMore').open=false;document.querySelector('#gradientEditor').open=true;document.querySelector('#gradientEditor').scrollIntoView()});await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'desktop-1440.png')});fs.writeFileSync(path.join(out,'preview-url.txt'),await page.evaluate(()=>location.origin+location.pathname+'#'+encodeState()));save('circle-preview', (await capture({w:1080,h:1080,crop:true})).png);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({time:new Date().toISOString(),checks,measurements,errors},null,2));console.log('ALPHA RESULT',checks.length,'checks passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
