// Transition width is part of the artwork, with identical native PNG output.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.THERMAL_PLAYWRIGHT_MODULE||'playwright');
const out=process.env.THERMAL_DETAIL_OUTPUT||'/private/tmp/thermal-export-detail/qa';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),checks=[],errors=[],measurements=[];try{
 const base=process.env.THERMAL_URL||'http://127.0.0.1:8766/tools/thermal-flow.html';
 const skip=s=>s.replace(/requestAnimationFrame\(loop\);\s*renderLookThumbnails\(\);/,'requestAnimationFrame(loop);');
 const setup=async (baseline,url=base)=>{const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.route('**/tools/thermal-flow.html*',async r=>{if(baseline)return r.fulfill({contentType:'text/html',body:skip(fs.readFileSync(baseline,'utf8'))});const response=await r.fetch();await r.fulfill({response,body:skip(await response.text())});});await p.goto(url);await p.waitForFunction(()=>typeof quick!=='undefined'&&quick);await p.evaluate(()=>_recording=true);return p};
 const page=await setup(),note=s=>{checks.push(s);console.log('PASS',s)};
 const snap=()=>page.evaluate(()=>stateRecord());
 const png=()=>page.evaluate(()=>{renderGL(...fullSize(),1);return prepareExportArtwork(...fullSize()).toDataURL()});
 const baseline=process.env.THERMAL_DETAIL_BASELINE_FILE;
 if(baseline){const old=await setup(baseline);for(const name of ['サーモフレーム','四隅フレア','溶融リボン','KVスワール','グラデ','ラジアル']){const render=name=>{applyPreset(PRESETS.find(p=>p.name===name));renderGL(180,240,1);return view.toDataURL()};assert.equal(await page.evaluate(render,name),await old.evaluate(render,name),name)}await old.close();note('zero sharpness keeps six existing looks pixel-identical');}
 await page.evaluate(()=>{applyPreset(PRESETS.find(p=>p.name==='グラデ'));Object.assign(state.field,{mode:'linear',linShape:'line',linAng:0,linWidth:400,warp1:0,warp2:0,curl:0,rise:0,gamma:50,contrast:50,offset:0,norm:false,linPosition:0});state.grain.amount=0;state.motion.on=false;state.mask.on=false;state.pins=[];state.studio=clone(DEFAULT_STUDIO);state.finish.bg=0;state.canvas={mode:'custom',w:1200,h:300};state.lut={stops:[{p:0,c:'#000000',h:0},{p:1,c:'#ffffff',h:0}],bands:0,invert:false,shift:0};buildLut();});
 for(const size of [1200,2400])for(const amount of [0,45,70]){
  const m=await page.evaluate(({size,amount})=>{state.studio.gradient.sharpness=amount;buildLut();renderGL(size,size/4,1);const a=new Uint8Array(size*4);gl.readPixels(0,size/8,size,1,gl.RGBA,gl.UNSIGNED_BYTE,a);const threshold=n=>{for(let x=0;x<size;x++)if(a[x*4]>=n)return x;return size};return{size,amount,width:(threshold(230)-threshold(26))/size,midpoint:threshold(128)/size,error:gl.getError(),buffer:gl.drawingBufferWidth};},{size,amount});measurements.push(m);assert.equal(m.error,0);assert.equal(m.buffer,size);assert.ok(Math.abs(m.midpoint-.5)<.002);}
 for(const size of [1200,2400]){const series=measurements.filter(m=>m.size===size);assert.ok(Math.abs(series[1].width/series[0].width-.55)<.01);assert.ok(Math.abs(series[2].width/series[0].width-.3)<.01);}
 note('transition widths narrow by 45% and 70%, preserve the midpoint, and match at 1× and 2×');
 await page.evaluate(()=>{state.studio.gradient.sharpness=45;buildLut();});const beforeExport=await snap();
 for(const mult of [1,2]){const expected=await page.evaluate(mult=>{const [w,h]=fullSize();renderGL(w*mult,h*mult,1);return prepareExportArtwork(w*mult,h*mult).toDataURL()},mult);const pending=page.waitForEvent('download');await page.evaluate(async mult=>{_recording=false;await exportStill('png',mult);_recording=true},mult);const download=await pending,file=path.join(out,'native-'+mult+'x.png');await download.saveAs(file);const bytes=fs.readFileSync(file);assert.equal(bytes.toString('base64'),expected.split(',')[1]);assert.equal(bytes.readUInt32BE(16),1200*mult);assert.deepEqual(await snap(),beforeExport);}
 note('real 1× and 2× PNG downloads match the native artwork exactly without changing the document');
 await page.evaluate(()=>{applyPreset(PRESETS.find(p=>p.name==='サーモフレーム'));setPalette(LUT_PRESETS.find(p=>p.name==='基準サーモ'));state.field.frameShape='circle';state.canvas={mode:'custom',w:360,h:360};refreshAll();document.querySelector('#gradientEditor').open=true;});
 const circleBefore=await snap(),soft=await png();
 const alpha=()=>page.evaluate(()=>{renderGL(...fullSize(),1);const a=new Uint8Array(view.width*view.height*4);gl.readPixels(0,0,view.width,view.height,gl.RGBA,gl.UNSIGNED_BYTE,a);return Array.from(a).filter((_,i)=>i%4===3)});const softAlpha=await alpha();
 await page.locator('#gradientSharpness input[type=range]').fill('45');await page.locator('#gradientSharpness input[type=range]').dispatchEvent('change');
 const crisp=await png(),circleAfter=await snap();assert.notEqual(crisp,soft);assert.deepEqual(circleAfter.field,circleBefore.field);assert.deepEqual(circleAfter.lut,circleBefore.lut);assert.deepEqual(circleAfter.grain,circleBefore.grain);assert.deepEqual(await alpha(),softAlpha);
 await page.evaluate(()=>undo());assert.equal(await png(),soft);await page.evaluate(()=>redo());assert.equal(await png(),crisp);
 note('the UI changes color blending, preserving circle transparency, geometry, palette and grain; undo/redo restores pixels');
 const project=await page.evaluate(()=>projectSnapshot());await page.evaluate(p=>loadProject(JSON.parse(JSON.stringify(p))),project);assert.equal(await png(),crisp);
 const url=await page.evaluate(()=>location.origin+location.pathname+'#'+encodeState());const fresh=await setup(null,url);await fresh.waitForFunction(()=>typeof quick!=='undefined'&&quick);await fresh.evaluate(()=>_recording=true);assert.ok(await fresh.evaluate(()=>{renderGL(...fullSize(),1);return prepareExportArtwork(...fullSize()).toDataURL()})===crisp,'fresh URL pixels');await fresh.close();
 await page.evaluate(p=>{delete p.studio.gradient.sharpness;loadProject(p)},project);assert.equal(await page.evaluate(()=>state.studio.gradient.sharpness),0);assert.equal(await png(),soft);
 assert.deepEqual(await page.evaluate(()=>[-5,150,'45',null].map(v=>normalizeStudio({gradient:{sharpness:v}}).gradient.sharpness)),[0,85,0,0]);
 note('JSON and fresh URL loads restore the exact image; older files stay at zero and invalid values are normalized');
 const keyed=await page.evaluate(()=>{state.motion.on=true;state.studio.gradient.sharpness=0;state.studio.animation.tracks=[{path:'studio.gradient.sharpness',enabled:true,keys:[{t:0,v:0,ease:'linear'},{t:8,v:70,ease:'linear'}]}];setAnimPhase(4);renderGL(240,240,1);const keyed=view.toDataURL(),restored=state.studio.gradient.sharpness;state.studio.animation.tracks=[];state.studio.gradient.sharpness=35;buildLut();renderGL(240,240,1);return{keyed,manual:view.toDataURL(),restored}});assert.equal(keyed.keyed,keyed.manual);assert.equal(keyed.restored,0);
 await page.evaluate(()=>{state.studio.gradient.interp='constant';refreshAll()});assert.equal(await page.locator('#gradientSharpness').isVisible(),false);await page.evaluate(()=>{state.studio.gradient.interp='ease';state.field.mode='linear';state.field.linShape='four';buildLut();refreshAll()});assert.equal(await page.locator('#gradientSharpness').isVisible(),false);
 note('keyframes match manual values and restore editing state; inapplicable controls are hidden');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({time:new Date().toISOString(),checks,measurements,errors},null,2));console.log('DETAIL RESULT',checks.length,'checks passed');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
