// Functional browser checks for the reference-inspired editor. Run with the same
// local server and Playwright module as thermal-flow.browser.cjs.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const {chromium}=require(process.env.THERMAL_PLAYWRIGHT_MODULE||'playwright');
const output=process.env.THERMAL_STUDIO_QA_OUTPUT||'/private/tmp/thermal-studio-qa';fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});const checks=[],errors=[];
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(60000);
  await page.goto(process.env.THERMAL_URL||'http://127.0.0.1:8766/tools/thermal-flow.html');await page.waitForFunction(()=>document.querySelectorAll('[data-ready=true]').length===PRESETS.length,{},{timeout:90000});
  const note=s=>{checks.push(s);console.log('PASS',s)};
  const record=()=>page.evaluate(()=>stateRecord());
  const pixel=()=>page.evaluate(()=>{renderGL(160,200,1);const out=view.toDataURL();renderGL(...previewSize(),1);return out});
  const range=async(label,value)=>{await page.getByRole('slider',{name:label,exact:true}).evaluate((input,v)=>{input.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true}));input.value=v;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));input.dispatchEvent(new PointerEvent('pointerup',{bubbles:true}));},value)};
  const saveDownload=async(action,name)=>{if(name!=='project.json'&&!(await page.locator('#exportMore').evaluate(e=>e.open)))await page.locator('#exportMore > summary').click();const [download]=await Promise.all([page.waitForEvent('download',{timeout:90000}),action()]);const file=path.join(output,name);await download.saveAs(file);return file};
  await page.getByRole('button',{name:'ルック: グラデ',exact:true}).click();await page.locator('#gradientEditor > summary').click();
  await page.evaluate(()=>{state.canvas.mode='custom';state.canvas.w=320;state.canvas.h=400;refreshAll()});const neutral=await record(),images={};
  for(const shape of ['line','radial','four','diamond','angle','bezier']){
   await page.getByRole('combobox',{name:'グラデーションの形',exact:true}).selectOption(shape);images[shape]=await pixel();
   await page.locator('#view').screenshot({path:path.join(output,'gradient-'+shape+'.png')});
  }
  assert.equal(new Set(Object.values(images)).size,6);note('six gradient geometries render distinct artwork');
  await page.evaluate(o=>restoreRecord(o),neutral);await page.getByRole('button',{name:'キャンバスで形を編集',exact:true}).click();
  const handles=await page.evaluate(()=>({handles:gradientHandles(),rect:document.querySelector('#studioEditCanvas').getBoundingClientRect().toJSON()}));
  const start=handles.handles[2].p,rect=handles.rect;const beforeDrag=await pixel();
  await page.mouse.move(rect.x+start[0]*rect.width,rect.y+Math.min(.99,Math.max(.01,1-start[1]))*rect.height);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.6,{steps:5});await page.mouse.up();assert.ok((await pixel())!==beforeDrag,'gradient handle drag must change the render');assert.ok(Math.abs((await record()).field.linAng-neutral.field.linAng)>20);
  await page.getByRole('button',{name:'↶ 戻す',exact:true}).click();assert.ok((await pixel())===beforeDrag,'undo must restore gradient drag');note('canvas gradient handles change the direction and width, and undo restores the original');
  const conversions=await page.evaluate(()=>{const colors=[[.1,.5,.9],[1,0,0],[.2,.2,.2]];return Object.fromEntries(['rgb','linear','hsv','hsl','xyz','lab','lch','oklab','oklch'].map(space=>[space,Math.max(...colors.flatMap(rgb=>spaceToRgb(rgbToSpace(rgb,space),space).map((v,i)=>Math.abs(v-rgb[i]))))]));});
  for(const [space,error]of Object.entries(conversions))assert.ok(error<.00001,space+' round trip '+error);
  const interpolations=[];await page.evaluate(()=>{state.lut.stops=[{p:0,c:'#ed3512'},{p:.4,c:'#258ace'},{p:1,c:'#ebd475'}];buildLut()});
  for(const mode of ['ease','cardinal','linear','bspline','constant','variable']){await page.getByRole('combobox',{name:'色の補間',exact:true}).selectOption(mode);if(mode==='variable')await range('補間の強さ',.75);interpolations.push(await pixel())}
  assert.equal(new Set(interpolations).size,6);await page.getByRole('combobox',{name:'色空間',exact:true}).selectOption('oklch');await range('繰り返し',3);await page.getByRole('checkbox',{name:'配色をミラー',exact:true}).check();assert.notEqual(await pixel(),interpolations.at(-1));note('nine color spaces round-trip accurately; six interpolation modes, repeat and mirror alter the artwork');
  const count=(await record()).lut.stops.length;await page.getByRole('button',{name:'複製',exact:true}).click();assert.equal((await record()).lut.stops.length,count+1);await page.getByRole('button',{name:'均等に配置',exact:true}).click();const ps=(await record()).lut.stops.map(s=>s.p).sort((a,b)=>a-b);assert.deepEqual(ps,[0,1/3,2/3,1]);await page.getByRole('button',{name:'色順を反転',exact:true}).click();await page.getByRole('button',{name:'削除',exact:true}).click();assert.equal((await record()).lut.stops.length,count);note('color stops can be duplicated, distributed, reversed and deleted');
  await page.evaluate(o=>{restoreRecord(o);studioEdit='';document.querySelector('#studioEditCanvas').style.pointerEvents='none'},neutral);
  await page.locator('#effectsEditor > summary').click();
  const moduleLabels={diffuse:'拡散 / Diffuse',noise:'ノイズ変形 / Noise',slit:'スリット / Slit',stretch:'引き伸ばし / Stretch',normal:'立体感 / Normal',distort:'手描き変形 / Distort',post:'後処理 / Postprocess'};
  const neutralPixels=await pixel();
  for(const key of ['diffuse','noise','slit','stretch','normal','post']){
   const toggle=page.getByRole('checkbox',{name:moduleLabels[key],exact:true});await toggle.check();if(key==='noise')await range('ノイズの強さ',20);assert.notEqual(await pixel(),neutralPixels,key+' must change pixels');await toggle.uncheck();assert.equal(await pixel(),neutralPixels,key+' off must restore pixels');
  }
  note('each effect changes the actual rendering when enabled and restores it when disabled');
  await page.getByRole('checkbox',{name:moduleLabels.noise,exact:true}).check();const noiseImages=[];
  for(const type of ['simplex','fbm','voronoi','aura','drift','curl','domain','seamless']){await page.getByRole('combobox',{name:'ノイズの種類',exact:true}).selectOption(type);noiseImages.push(await pixel())}assert.equal(new Set(noiseImages).size,8);await page.getByRole('checkbox',{name:moduleLabels.noise,exact:true}).uncheck();
  await page.getByRole('checkbox',{name:moduleLabels.slit,exact:true}).check();await range('スリット数',7);const slitImages=[];for(const type of ['linear','circular','polygon','wave']){await page.getByRole('combobox',{name:'スリットの形',exact:true}).selectOption(type);slitImages.push(await pixel())}assert.equal(new Set(slitImages).size,4);await page.getByRole('checkbox',{name:moduleLabels.slit,exact:true}).uncheck();note('all eight noise algorithms and four slit geometries produce distinct results');
  await page.getByRole('checkbox',{name:moduleLabels.distort,exact:true}).check();await page.getByRole('button',{name:'キャンバスで描く',exact:true}).click();
  const box=await page.locator('#studioEditCanvas').boundingBox();const beforeBrush=await pixel();await page.mouse.move(box.x+box.width*.45,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width*.7,box.y+box.height*.6,{steps:8});await page.mouse.up();assert.ok((await record()).studio.distort.strokes.length>3);assert.notEqual(await pixel(),beforeBrush);await page.locator('#btnUndo').click();assert.equal(await pixel(),beforeBrush);await page.locator('#btnRedo').click();assert.notEqual(await pixel(),beforeBrush);note('a brush stroke deforms the artwork and is one undo/redo step');
  await page.evaluate(o=>{restoreRecord(o);studioEdit='';document.querySelector('#studioEditCanvas').style.pointerEvents='none'},neutral);
  await page.evaluate(o=>{restoreRecord(o);studioEdit='';document.querySelector('#studioEditCanvas').style.pointerEvents='none'},neutral);
  await page.getByRole('button',{name:'パネルを分離',exact:true}).click();const floatBefore=await page.locator('#gradientEditor').boundingBox();const summary=await page.locator('#gradientEditor > summary').boundingBox();await page.mouse.move(summary.x+80,summary.y+10);await page.mouse.down();await page.mouse.move(summary.x+105,summary.y+35,{steps:3});await page.mouse.up();const floatAfter=await page.locator('#gradientEditor').boundingBox();assert.ok(floatAfter.x>floatBefore.x+15);await page.getByRole('button',{name:'パネルを戻す',exact:true}).click();note('the gradient editor detaches into a draggable, resizable panel and returns to the sidebar');
  await page.getByRole('checkbox',{name:moduleLabels.post,exact:true}).check();const postRenders=[];for(const type of ['mirror','kaleidoscope','prism','voronoi']){await page.getByRole('combobox',{name:'後処理の種類',exact:true}).selectOption(type);postRenders.push(await pixel())}assert.equal(new Set(postRenders).size,4);
  await page.getByRole('combobox',{name:'後処理の種類',exact:true}).selectOption('distort');await page.getByRole('button',{name:'後処理で描く',exact:true}).click();const postBefore=await pixel(),postBox=await page.locator('#studioEditCanvas').boundingBox();await page.mouse.move(postBox.x+postBox.width*.4,postBox.y+postBox.height*.5);await page.mouse.down();await page.mouse.move(postBox.x+postBox.width*.6,postBox.y+postBox.height*.6,{steps:5});await page.mouse.up();assert.ok((await record()).studio.post.strokes.length>0);assert.ok((await pixel())!==postBefore);await page.locator('#btnUndo').click();assert.ok((await pixel())===postBefore);note('postprocess symmetry modes render independently and postprocess brush edits undo correctly');
  await page.evaluate(o=>{restoreRecord(o);studioEdit='';document.querySelector('#studioEditCanvas').style.pointerEvents='none'},neutral);await page.getByRole('checkbox',{name:moduleLabels.stretch,exact:true}).check();const noGlow=await page.evaluate(()=>{renderGL(160,200,1);return composeArtwork(160,200).toDataURL()});await page.getByRole('checkbox',{name:'グローを重ねる',exact:true}).check();assert.ok((await page.evaluate(()=>{renderGL(160,200,1);return composeArtwork(160,200).toDataURL()}))!==noGlow);note('glow participates in the composed artwork used by preview and exports');
  await page.evaluate(o=>restoreRecord(o),neutral);await page.getByRole('checkbox',{name:'縦横比を固定',exact:true}).check();await page.getByRole('spinbutton',{name:'キャンバス幅',exact:true}).fill('400');await page.getByRole('spinbutton',{name:'キャンバス高さ',exact:true}).focus();assert.equal((await record()).canvas.h,500);await page.getByRole('button',{name:'幅・高さを交換',exact:true}).click();assert.deepEqual([(await record()).canvas.w,(await record()).canvas.h],[500,400]);note('custom canvas sizes preserve the locked aspect ratio and swap width and height');
  await page.evaluate(o=>restoreRecord(o),neutral);await page.locator('#imageEditor > summary').click();const fixture=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=64;c.height=64;const x=c.getContext('2d');x.fillStyle='#20a050';x.fillRect(16,16,32,32);return c.toDataURL()});await page.locator('#studio-image-file').setInputFiles({name:'alpha.png',mimeType:'image/png',buffer:Buffer.from(fixture.split(',')[1],'base64')});await page.waitForFunction(()=>overlayImage&&overlayImage.src===state.studio.image.data);
  await page.getByRole('combobox',{name:'画像の使い方',exact:true}).selectOption('mask');const alpha=await page.evaluate(()=>{renderGL(160,200,1);const c=composeArtwork(160,200);const p=c.getContext('2d').getImageData(0,0,160,200).data;return[p[3],p[(100*160+80)*4+3]]});assert.equal(alpha[0],0);assert.ok(alpha[1]>0);
  const imageProject=await page.evaluate(()=>projectSnapshot());await page.getByRole('button',{name:'画像を外す',exact:true}).last().click();await page.evaluate(o=>loadProject(o),imageProject);await page.waitForFunction(()=>overlayImage&&overlayImage.src===state.studio.image.data);assert.equal((await record()).studio.image.data,fixture);note('transparent image masks composite correctly and the original image survives project restoration');
  await page.evaluate(o=>restoreRecord(o),neutral);
  const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M10 20 C30 90 70 10 90 80"/></svg>';
  await page.getByRole('combobox',{name:'グラデーションの形',exact:true}).selectOption('bezier');await page.locator('#bezierSvgInput').setInputFiles({name:'curve.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await page.waitForFunction(()=>state.studio.gradient.paths.length===4);assert.notEqual(await pixel(),images.bezier);note('SVG path import creates editable Bezier paths');
  await page.evaluate(o=>restoreRecord(o),neutral);
  await page.getByRole('checkbox',{name:'モーション',exact:true}).check();await page.getByRole('button',{name:'タイムラインを開く',exact:true}).click();
  await page.evaluate(()=>{state.motion.evo=0;state.motion.sway=0;state.motion.hue=0;state.motion.loopSec=2;seekTime(0);state.field.linAng=270;addKeyframe('field.linAng');seekTime(1);state.field.linAng=0;addKeyframe('field.linAng');seekTime(2);state.field.linAng=270;addKeyframe('field.linAng');seekTime(0)});
  const frame0=await pixel();await page.evaluate(()=>seekTime(1));const frame1=await pixel();assert.notEqual(frame0,frame1);await page.evaluate(()=>seekTime(2));assert.equal(frame0,await pixel());
  await page.getByRole('button',{name:'グラフ',exact:true}).click();await page.getByRole('combobox',{name:'キーフレームの補間',exact:true}).selectOption('curve');await page.getByRole('checkbox',{name:'全体のタイムリマップ',exact:true}).check();assert.equal((await record()).studio.animation.remap,true);await page.getByRole('checkbox',{name:'全体のタイムリマップ',exact:true}).uncheck();await page.evaluate(()=>seekTime(.5));
  await page.screenshot({path:path.join(output,'timeline.png')});note('keyframes interpolate, loop endpoints match, and timeline/remap controls are available');
  await page.evaluate(()=>{state.canvas.mode='custom';state.canvas.w=160;state.canvas.h=200;state.motion.loopSec=1;state.studio.animation.fps=24;state.studio.animation.tracks[0].keys=[{t:0,v:270,ease:'linear'},{t:1,v:0,ease:'linear'}];refreshAll()});
  await page.locator('#exportMore > summary').click();
  const zip=await saveDownload(()=>page.getByRole('button',{name:'連番PNG ZIP',exact:true}).click(),'frames.zip');
  const mov=await saveDownload(()=>page.getByRole('button',{name:'ロスレスMOV',exact:true}).click(),'lossless.mov');
  execFileSync(process.env.FFMPEG||'ffmpeg',['-v','error','-i',mov,'-f','null','-']);const metadata=JSON.parse(execFileSync(process.env.FFPROBE||'ffprobe',['-v','error','-show_streams','-of','json',mov],{encoding:'utf8'}));const stream=metadata.streams[0];assert.equal(stream.codec_name,'png');assert.equal(stream.width,160);assert.equal(stream.height,200);assert.equal(+stream.nb_frames,24);assert.equal(stream.r_frame_rate,'24/1');
  const zipInfo=JSON.parse(execFileSync('python3',['-c','import zipfile,json,sys,hashlib; z=zipfile.ZipFile(sys.argv[1]); p=[n for n in z.namelist() if n.endswith(".png")]; print(json.dumps({"n":len(p),"different":len({hashlib.sha256(z.read(n)).hexdigest() for n in p}),"bad":z.testzip()}))',zip],{encoding:'utf8'}));assert.equal(zipInfo.n,24);assert.ok(zipInfo.different>20);assert.equal(zipInfo.bad,null);note('PNG ZIP contains every distinct frame; lossless MOV is decoded by ffprobe as 24 PNG frames at the requested dimensions and fps');
  const jpg=await saveDownload(()=>page.getByRole('button',{name:'JPG',exact:true}).click(),'still.jpg');assert.equal(fs.readFileSync(jpg).subarray(0,2).toString('hex'),'ffd8');const webp=await saveDownload(()=>page.getByRole('button',{name:'WebP',exact:true}).click(),'still.webp');assert.equal(fs.readFileSync(webp).subarray(8,12).toString(),'WEBP');note('JPG and WebP export contain the requested image formats');
  await page.keyboard.press('Escape');await page.locator('#projectEditor > summary').click();await page.getByRole('textbox',{name:'作品名',exact:true}).fill('<b>保存テスト</b>');await page.getByRole('button',{name:'このブラウザに保存',exact:true}).click();assert.equal(await page.locator('#savedProjects b').count(),0);
  const project=await saveDownload(()=>page.getByRole('button',{name:'JSONで保存',exact:true}).click(),'project.json');const saved=JSON.parse(fs.readFileSync(project));assert.ok(saved.project.studio.animation.tracks.length);await page.evaluate(()=>{state.studio.animation.tracks=[];state.studio.noise.on=true;refreshAll()});await page.locator('#projectFile').setInputFiles(project);await page.waitForFunction(()=>state.studio.animation.tracks.length>0);assert.equal((await record()).studio.noise.on,false);note('projects persist full animation/effect settings and render user-provided names as text');
  await page.evaluate(()=>{state.motion.on=false;timelineOpen=false;state.studio.slit.on=true;state.studio.slit.type='linear';state.studio.slit.count=4;refreshAll()});const slits=await saveDownload(()=>page.getByRole('button',{name:'スリット別PNG ZIP',exact:true}).click(),'slits.zip');const slitCount=+execFileSync('python3',['-c','import zipfile,sys; print(len(zipfile.ZipFile(sys.argv[1]).namelist()))',slits],{encoding:'utf8'});assert.equal(slitCount,4);note('individual slit export produces one PNG for each slit');
  await page.evaluate(()=>{state.motion.on=true;state.motion.loopSec=4;playback.playing=false;refreshAll()});const beforeCancel=await record();let cancelledDownloads=0;const onDownload=()=>cancelledDownloads++;page.on('download',onDownload);if(!(await page.locator('#exportMore').evaluate(e=>e.open)))await page.locator('#exportMore > summary').click();await page.getByRole('button',{name:'連番PNG ZIP',exact:true}).click();await page.locator('#exportDialog').waitFor({state:'visible'});await page.getByRole('button',{name:'キャンセル',exact:true}).click();await page.waitForFunction(()=>!_recording);await page.waitForTimeout(150);page.off('download',onDownload);assert.equal(cancelledDownloads,0);assert.deepEqual(await record(),beforeCancel);note('cancelling a frame export saves no partial file and restores the editable project');
  console.log('RENDER INFO',await page.evaluate(()=>({ms:_ms,renderer:gl.getParameter(gl.RENDERER)})));assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'report.json'),JSON.stringify({time:new Date().toISOString(),checks,errors,conversions,stream},null,2));console.log('STUDIO RESULT',checks.length,'checks passed');
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
